language: java
services: postgresql
before_install: psql -c 'CREATE DATABASE acebook;' -U postgres
install:
  - brew install maven
  - mvn clean install
before_script: ls target/
script:
  - mvn verify
  - mvn test
