language: java
jdk: openjdk13
services: postgresql
before_install:
  - psql -c 'CREATE DATABASE acebook_test;' -U postgres
  - sudo apt-get install tree
install:
  - tree
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -V
before_script: ls
script:
  - mvn verify
  - mvn test
